project:
  type: website
  output-dir: docs

execute:
  cache: true

website:
  title: "Paulius Alaburda"
  site-url: "https://alaburda.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog
      - href: talks.qmd
        text: Talks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



