---
title: "Everything is an API"
author: "Paulius Alaburda"
date: "2021-03-09"
categories: [thoughts]
draft: true
---

In software development, two pieces of software usually communicate through an Application Programming Interface (API). APIs can differ based on the maturity of the product and on its intended use but all of them boil down to letting different applications communicate with each other. For example, your weather app asks data from a weather data service through an API. If the weather data service suddenly changes its API, the weather app developer has to adapt to these changes as well. Because of this, APIs tend to be stable or at least well documented as to how they work.

Adapting to API changes requires time and energy and I think regular users are no different. Whenever Facebook changes its design and layout, we have to put mental energy to unlearn how we used to use an app and adapt to the new interface. Because of this, user adoption can be difficult if you make drastic changes.

So that's human to software relationships, but what about human to human relationships? I have a strong suspicion I am reinventing the wheel by looking at trust and consistency from a software point. But the one thing that I learn from this is that consistency matters a lot. People set expectations about you and if you keep changing your way of working, you ask people to spend time and energy to adapt to you. If you are a manager, changing goalposts and priorities will not only force fatigue from shifting focus but also force your reports to spend time figuring you out.
