---
title: "My Favourite Things Books"
author: "Paulius Alaburda"
date: "2021-06-09"
categories: [books]
---

This is not a comprehensive guide but more of a compendium of links and sources for future self-reference. I suspect some of these might become deprecated or some of the recommended lists will not hold up to time. Nonetheless, I think it might be interesting to capture this snapshot and compare to my scope next year.

I think society overrates book recommendations - we have yearly book lists, best-of clickbait articles and influencers trying to push whatever would seem acceptable or commendable by society. As in, if everyone's talking about it, it must mean it's good? However, we live in a time where we have access to the world's Library of Alexandria in the form of LibGen and we are seeing more literature in translation (for example, this year [a Latvian book has finally been translated into Chinese](http://www.latvianliterature.lv/en/news/top-ten-latvian-literature-moments-of-2019)!). With that, this list is more of an atlas where to potentially find good books. I promise not to name a single book in this post!

## Awards, longlists, shortlists...

1. [Republic of Consciousness Prize](https://www.republicofconsciousness.com/the-rag/the-republic-of-consciousness-2020-longlist) - a prize awarded to small publishers, among which are publishers such as And Other Stories (lit in translation) and Fitzcarraldo Editions.
2. [Swansea University Dylan Thomas Prize](https://www.swansea.ac.uk/press-office/news-events/news/2020/01/international-and-under-represented-voices-dominate-the-longlist-for-the-15th-anniversary-of-the-swansea-university-dylan-thomas-prize-.php) - keeping it here for posterity, haven't checked it out.

## Review websites

1. [The Complete Review](http://www.complete-review.com/saloon/index.htm)
2. [Tyler Cowen's book recommendations](https://marginalrevolution.com/marginalrevolution/category/books)

## Literary websites and blogs

1. [The Complete Review](https://www.complete-review.com/saloon/index.htm) - possibly the only website you might need
2. [Biblioklept](https://biblioklept.org/) - regularly updated and includes a lot of contemporary artwork
3. [Waggish](https://www.waggish.org/2019/david-auerbachs-books-of-the-year-2019/) - rarely updates but the yearly lists are treasure troves of good books.
4. [Seminary Co-op's Bookstore](https://www.semcoop.com/blog/) - based in Chicago, they release weekly recommendations, podcasts and is overall a great jumping point for worldly literature.
5. [The Millions](https://themillions.com/)
6. [Two Lines Press Blog](https://www.catranslation.org/blog/)
7. [Quimby's](https://www.quimbys.com/blog/) - does it tell I'm partial to Chicago? Quimby's runs a weekly blog with new additions to their selection.

## Honestly, why would you read books when you can read blogposts or book summaries?

1. [Asymptote](https://www.asymptotejournal.com/)
2. [SlateStarCodex](https://slatestarcodex.com/)

## Book Publishers and Distributors I keep an eye on

1. [Inpress Books](https://inpressbooks.co.uk/) - they are not publishers but their selection seems pretty unique.
2. [Fitzcarraldo Editions](https://fitzcarraldoeditions.com/) - it's Fitz! Their books have won numerous awards, so there is usually no wrong choice within their catalogue.
3. [And Other Stories](https://www.andotherstories.org/books/) - they offer a subscription service but overall their offering is lovely.
4. [Stripe Press](https://press.stripe.com/) - the quality of the content and of the books themselves is excellent.
5. [Boss Fight Books](https://bossfightbooks.com/) - publishes books about video games. Have not read anything yet, but the variety is excellent and makes for a great gift to a friend.
6. [Thames and Hudson](https://thamesandhudson.com/) - they have published Nature's Palette, which in and of itself is already amazing.
7. [Princeton University Press](https://press.princeton.edu/books) - I feel weird suggesting a university press but their Ancient Wisdom for Modern Readers series looks like a great present.
8. [Fantagraphics](https://www.fantagraphics.com/) - their offerings may vary in quality but they release impressive graphic volumes that may draw your eye.
9. [Drawn & Quarterly](https://drawnandquarterly.com/) - the Canadian publisher focuses more on a family-friendly offering of graphic novels but they are wonderful nonetheless.
